### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by mlgruby** [AtomLinter/linter-lintr#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: linux 3.16.0-34-generic
**Thrown From**: [linter-lintr](https://github.com/AtomLinter/linter-lintr) package, v0.0.1

### Stack Trace

Failed to activate the linter package

```
At Cannot find module '/home/satya/.atom/packages/linter-lintr/lib/linter-lintr'

Error: Cannot find module '/home/satya/.atom/packages/linter-lintr/lib/linter-lintr'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at LinterInitializer.activate (/home/satya/.atom/packages/linter/lib/init.coffee:87:30)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:225:19)
    at /usr/share/atom/resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:199:14)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Ensime, v0.3.2
autocomplete-plus-python-jedi, v0.2.6
linter, v0.12.0
linter-lintr, v0.0.1
linter-lua, v0.1.5
linter-python-pep8, v0.2.0
python-isort, v0.0.6
run-in-terminal, v0.2.0
terminal-panel, v1.10.0

# Dev
No dev packages
```

**Comment by hd-deman** [comment]
Its not yet ready
