### ISSUE TITLE
Failed to activate the linter-lintr package

### ISSUE THREAD

**Issue by JeffLabonte** [AtomLinter/linter-lintr#103]
[Enter steps to reproduce:]

1. Update packages
2. Open Atom

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [linter-lintr](https://github.com/AtomLinter/linter-lintr) package 1.1.4

### Stack Trace

Failed to activate the linter-lintr package

```
At Cannot find module 'nuclide-commons-atom/text-event'

Error: Cannot find module 'nuclide-commons-atom/text-event'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _load_textEvent (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:24:23)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:225:110)
    at createAdapter (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapterFactory.js:30:12)
    at Activation.consumeLinterProvider (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/main.js:140:97)
    at /packages/atom-ide-ui/modules/nuclide-commons-atom/createPackage.js:51:38)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:448:77)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:258:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-django 0.3.2 
atom-ide-ui 0.7.1 
atom-latex 0.8.2 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-bash-builtins 0.3.5 
autocomplete-cmake 0.3.1 
autocomplete-html-entities 0.2.0 
autocomplete-java 1.2.7 
autocomplete-jquery-mobile 0.2.2 
autocomplete-python 1.10.5 
bottom-dock 0.4.4 
build 0.70.0 
build-cmake 0.11.0 
busy-signal 1.4.3 
django-templates 0.5.0 
docker 0.8.0 
dockerletion 0.2.0 
gpp-compiler 3.0.7 
gradle-manager 0.0.5 
gulp-control 0.5.0 
ide-cpp 0.0.3 
ide-csharp 0.6.1 
ide-flowtype 0.17.6 
ide-html 0.4.1 
ide-java 0.7.0 
ide-php 0.7.4 
ide-typescript 0.7.2 
intentions 1.1.5 
java-generator 2.2.3 
jQuery 1.2.5 
jquery-snippets 11.0.0 
language-cmake 1.1.0 
language-cpp14 0.6.2 
language-django 0.1.1 
language-docker 1.1.8 
language-gradle 0.0.5 
language-latex 1.1.1 
language-markdown 0.25.1 
language-r 0.4.2 
latex-completions 0.3.3 
latextools 0.8.5 
linter 2.2.0 
linter-gcc 0.7.1 
linter-lintr 1.1.4 
linter-ui-default 1.6.10 
platformio-ide-terminal 2.8.0 
python-indent 1.1.4 
python-tools 0.6.9 
r-exec 0.5.0 
scss-media-queries 0.4.0 
vim-mode-plus 1.26.0 
```

**Comment by Arcanemagus** [comment]
This error has nothing to do with this package, and looks to be the result of an old version of `atom-ide-ui`.
