### ISSUE TITLE
"there is no package called 'lintr'" error in v1.1.0

### ISSUE THREAD

**Issue by bmwilly** [AtomLinter/linter-lintr#75]
After upgrading to 1.1.0, doing anything in Atom results in the error 
```
Error: Error in library(lintr) : there is no package called ‘lintr’
Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
Execution halted
    at ChildProcess.<anonymous> (/Users/brandon/.atom/packages/linter-lintr/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

I do have lintr installed. Downgrading to 1.0.4 fixes the problem. 

Atom v1.10.2 and 
```
> library(lintr)
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] lintr_1.0.0

loaded via a namespace (and not attached):
[1] lazyeval_0.2.0.9000 magrittr_1.5        rex_1.1.1
```

**Comment by Arcanemagus** [comment]
How do you have `lintr` installed? The only difference between v1.0.4 and v1.1.0 is the addition of `--vanilla` to the parameters passed to `R`. This works perfectly fine with the recommended method of installation, but may be causing you issues?

**Comment by bmwilly** [comment]
@Arcanemagus thanks for the quick response. 

I installed it in the normal way using `install.packages('lintr')`.

**Comment by Arcanemagus** [comment]
If you run `R --vanilla` and then in that shell run `installed.packages()` is `lintr` listed? (It's in the last section of the list for me)

**Comment by bmwilly** [comment]
Aha! No, it isn't. I understand what's going on now. I have an `.Rprofile` that modifies `.libPaths()` so that all my packages are installed elsewhere. The obvious workaround is to just install `lintr` after `R --vanilla`. Thank you - sorry for wasting your time.

**Comment by Arcanemagus** [comment]
No problem, I'm glad my fumbling around helped as I have no real idea how `R` works 😛.
