### ISSUE TITLE
Error: Error in library(lintr) : there is no package called ‘lintr’

### ISSUE THREAD

**Issue by BigMcLargeHuge** [AtomLinter/linter-lintr#82]
Atom v1.11.2

When I attempt to install the lintr package I get the following error message.

```
Error: Error in library(lintr) : there is no package called ‘lintr’
Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
Execution halted
    at ChildProcess.<anonymous> (/home/sam/.atom/packages/linter-lintr/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

**Comment by Arcanemagus** [comment]
Have you followed the [Installation instructions](https://github.com/AtomLinter/linter-lintr#installation)? It looks like you don't have `lintr` installed.

**Comment by BigMcLargeHuge** [comment]
My apologies, I had read that I needed `linter` installed.  Thanks for setting me straight; great plugin by the way!
