### ISSUE TITLE
Tab indented files break the linter

### ISSUE THREAD

**Issue by c22** [AtomLinter/linter-lintr#84]
If you try linting a file that's tab indented, instead of getting "Use two spaces to indent, never tabs." you'll crash the linter with a message similar to the following:

> Error: Column start (23) greater than line length (18)
>     at Object.rangeFromLineNumber (/Users/c22/.atom/packages/linter-lintr/node_modules/atom-linter/lib/index.js:179:11)
>     at /Users/c22/.atom/packages/linter-lintr/lib/main.js:73:32

**Comment by Arcanemagus** [comment]
This is almost always a bug in the provider. In this case it looks like `lintr` is following that advice when it reported the point, so it's saying that the error is at column 23 on a line that only has 18 characters.

**Comment by c22** [comment]
I'm not too familiar with the specifics of how providers interact with atom linter plugins, but I recall at the time that lintr itself was not crashing with the same file. I have not done any R work in a while though, I can test this again when I have some free time.

**Comment by Arcanemagus** [comment]
If it doesn't _know_ that it's reporting a position that doesn't exist, it's not going to crash or throw an error about it. This is a relatively common bug with linters in general.
